name: args_simple
description: a simple argument parser and handler, integrated with JSON and dart:io.
version: 1.1.0
homepage: https://github.com/gmpassos/args_simple

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
   collection: ^1.18.0
   yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.9
  dependency_validator: ^3.2.2
  coverage: ^1.7.1
